"""add passport template tables

Revision ID: d21cbbf86149
Revises: 074668bbdd69
Create Date: 2026-07-22 22:49:08.673180
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd21cbbf86149'
down_revision: str | Sequence[str] | None = '074668bbdd69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passport_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name='ck_template_status'),
    sa.CheckConstraint('version >= 1', name='ck_template_version_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'category_id', 'name', 'version', name='uq_template_owner_category_name_version')
    )
    op.create_index(op.f('ix_passport_templates_category_id'), 'passport_templates', ['category_id'], unique=False)
    op.create_index(op.f('ix_passport_templates_organization_id'), 'passport_templates', ['organization_id'], unique=False)
    op.create_table('template_fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('access_level', sa.String(length=50), server_default='public', nullable=False),
    sa.Column('validation_rules', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint("access_level IN ('public', 'manufacturer')", name='ck_template_field_access_level'),
    sa.CheckConstraint("data_type IN ('text', 'integer', 'decimal', 'boolean', 'date')", name='ck_template_field_data_type'),
    sa.CheckConstraint('display_order >= 0', name='ck_template_field_display_order'),
    sa.ForeignKeyConstraint(['template_id'], ['passport_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'code', name='uq_template_field_code')
    )
    op.create_index(op.f('ix_template_fields_template_id'), 'template_fields', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_fields_template_id'), table_name='template_fields')
    op.drop_table('template_fields')
    op.drop_index(op.f('ix_passport_templates_organization_id'), table_name='passport_templates')
    op.drop_index(op.f('ix_passport_templates_category_id'), table_name='passport_templates')
    op.drop_table('passport_templates')
    # ### end Alembic commands ###
